language: python

install:
  - pip install -r requirements.txt
  - pip install pandas
  - pip install tenacity
stages:
  - name: build36
  - name: build37
  - name: build38
  - name: build39
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: build36
      script: "./build.sh"
      python: '3.6'
    - stage: build37
      script: "./build.sh"
      python: '3.7'
    - stage: build38
      script: "./build.sh"
      python: '3.8'
    - stage: build39
      script: "./build.sh"
      python: '3.9'
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        username: __token__
        password: $PYPI_API_KEY
        on:
          branch: master