language: python

install:
  - pip install -r requirements.txt
  - pip install pandas
  - pip install tenacity
stages:
  - name: build
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: build
      script: "./build.sh"
      python:
        - "3.6"
        - "3.7"
        - "3.8"
        - "3.9"
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        username: __token__
        password: $PYPI_API_KEY
        on:
          branch: master